name: Deploy to production

on:
  push:
    branches: [ master]

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up date
      id: date
      run: |
        echo "::set-output name=date::$(date +'%m/%d/%Y:%H:%M')"

    - name: Set up API version
      id: ghd
      uses: proudust/gh-describe@v1.5.4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Setup Environment Variables
      run: |
        echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
        echo "DB_DSN=${{ secrets.DB_DSN }}" >> .env
        echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env
        echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
        echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> .env
        echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env
        echo "SMTP_SENDER=${{ secrets.SMTP_SENDER }}" >> .env


    - name: Build, tag, and push docker image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: blogpost
        IMAGE_TAG: ${{ steps.ghd.outputs.describe }}
      run: |
        docker build --build-arg VERSION=${{ steps.ghd.outputs.describe }} --build-arg CURRENT_TIME=${{ steps.date.outputs.date }} -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f app.dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG